-- Sample Records for Secure Chat Database
-- These are example user records showing the database structure with actual data

USE securechat;

-- Sample User 1: alice@example.com
-- Password: testpass123
-- Salt: 0ccc849ff80aa1e12a1e0ce02e0fa0d4 (16 bytes, randomly generated)
-- pwd_hash: SHA256(salt || password) = a085f8e7a3121f9da9e23c52d787fe06d5569a8c88e06875fce4fb3404245010
INSERT INTO users (email, username, salt, pwd_hash) VALUES
('alice@example.com', 'alice', 
 UNHEX('0ccc849ff80aa1e12a1e0ce02e0fa0d4'), 
 'a085f8e7a3121f9da9e23c52d787fe06d5569a8c88e06875fce4fb3404245010');

-- Sample User 2: bob@example.com  
-- Password: securepass456
-- Salt: (randomly generated 16 bytes)
-- pwd_hash: SHA256(salt || password) in hex format (64 characters)
INSERT INTO users (email, username, salt, pwd_hash) VALUES
('bob@example.com', 'bob',
 UNHEX('f1e2d3c4b5a6978012345678901234cd'),
 '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5');

-- Note: In production, these would be generated by the registration process
-- The salt is randomly generated for each user
-- The pwd_hash is computed as: SHA256(salt || password) and stored as hex string

-- To view sample records:
-- SELECT id, email, username, HEX(salt) as salt_hex, pwd_hash, created_at FROM users;

